<?php
declare(strict_types=1);

function svci_normalize_catalog_url(string $url): string
{
    $parts = parse_url($url);
    if (!is_array($parts)) {
        return $url;
    }

    $scheme = strtolower((string)($parts['scheme'] ?? 'https'));
    $host = strtolower((string)($parts['host'] ?? 'shopvivaliz.com.br'));
    $path = (string)($parts['path'] ?? '');

    if ($host !== 'shopvivaliz.com.br' || rtrim($path, '/') !== '/catalogo') {
        return $url;
    }

    $query = [];
    if (isset($parts['query']) && $parts['query'] !== '') {
        parse_str((string)$parts['query'], $query);
    }

    $encodedQuery = $query !== []
        ? '?' . http_build_query($query, '', '&', PHP_QUERY_RFC3986)
        : '';

    return $scheme . '://shopvivaliz.com.br/catalogo/' . $encodedQuery;
}

function svci_catalog_canonical_for_request(): string
{
    $params = [];

    $categoryRaw = $_GET['categoria'] ?? '';
    $category = is_scalar($categoryRaw) ? trim((string)$categoryRaw) : '';
    if ($category !== '') {
        $params['categoria'] = $category;
    }

    $pageRaw = $_GET['pagina'] ?? 1;
    $page = is_scalar($pageRaw) ? max(1, (int)$pageRaw) : 1;
    $searchRaw = $_GET['q'] ?? $_GET['busca'] ?? '';
    $search = is_scalar($searchRaw) ? trim((string)$searchRaw) : '';

    // Paginated category/catalog pages are distinct crawlable pages. Search
    // result pages remain noindex and keep the base/category canonical policy.
    if ($page > 1 && $search === '') {
        $params['pagina'] = $page;
    }

    return 'https://shopvivaliz.com.br/catalogo/'
        . ($params !== [] ? '?' . http_build_query($params, '', '&', PHP_QUERY_RFC3986) : '');
}

// /catalogo/ is the final URL chosen by Apache for this physical directory.
// Normalize legacy slashless links generated by catalogo.php at render time so
// crawlers and users do not pay a 301 on every category/search/pagination link.
ob_start(static function (string $html): string {
    $html = preg_replace_callback(
        '#https://shopvivaliz\.com\.br/catalogo/?(?:\?[^"\']*)?(?=["\'])#',
        static fn(array $match): string => svci_normalize_catalog_url($match[0]),
        $html
    ) ?? $html;
    $html = preg_replace_callback(
        '#(?<=["\'])/catalogo/?(?:\?[^"\']*)?(?=["\'])#',
        static function (array $match): string {
            $url = 'https://shopvivaliz.com.br' . $match[0];
            return substr(svci_normalize_catalog_url($url), strlen('https://shopvivaliz.com.br'));
        },
        $html
    ) ?? $html;

    $canonical = svci_catalog_canonical_for_request();
    $escapedCanonical = htmlspecialchars($canonical, ENT_QUOTES, 'UTF-8');

    $html = preg_replace_callback(
        '#<link\s+rel="canonical"\s+href="[^"]*">#i',
        static fn(array $match): string => '<link rel="canonical" href="' . $escapedCanonical . '">',
        $html,
        1
    ) ?? $html;
    $html = preg_replace_callback(
        '#<meta\s+property="og:url"\s+content="[^"]*">#i',
        static fn(array $match): string => '<meta property="og:url" content="' . $escapedCanonical . '">',
        $html,
        1
    ) ?? $html;

    return $html;
});

require dirname(__DIR__) . '/catalogo.php';