<?php
declare(strict_types=1);
function sv_ar_gmail_base64url_decode(string $data): string { $p=strtr($data,'-_','+/');$pad=strlen($p)%4;if($pad!==0)$p.=str_repeat('=',4-$pad);$d=base64_decode($p,true);return is_string($d)?$d:''; }
function sv_ar_gmail_flatten_parts(array $part): array { $parts=[$part];foreach((array)($part['parts']??[]) as $child)if(is_array($child))$parts=array_merge($parts,sv_ar_gmail_flatten_parts($child));return $parts; }
function sv_ar_gmail_extract_full_message(array $message): array { $payload=is_array($message['payload']??null)?$message['payload']:[];$headers=[];foreach((array)($payload['headers']??[]) as $h)if(is_array($h))$headers[strtolower((string)($h['name']??''))]=(string)($h['value']??'');$plain='';$html='';foreach(sv_ar_gmail_flatten_parts($payload) as $part){$mime=strtolower((string)($part['mimeType']??''));$data=(string)($part['body']['data']??'');if($data==='')continue;$decoded=sv_ar_gmail_base64url_decode($data);if($mime==='text/plain'&&$plain==='')$plain=$decoded;elseif($mime==='text/html'&&$html==='')$html=$decoded;}if($plain==='')$plain=trim(html_entity_decode(strip_tags($html),ENT_QUOTES|ENT_HTML5,'UTF-8'));return ['id'=>(string)($message['id']??''),'thread_id'=>(string)($message['threadId']??''),'from'=>$headers['from']??'','subject'=>$headers['subject']??'','body'=>$plain,'internal_date_ms'=>(string)($message['internalDate']??'')]; }
function sv_ar_gmail_default_query(): string { return 'from:(donotreply@amazon.com OR amazon.com.br) -category:promotions'; }
final class SvAmazonRecoveryGmailClient { private ?string $accessToken=null;private Closure $transport;public function __construct(private string $clientId,private string $clientSecret,private string $refreshToken,private string $user='me',?Closure $transport=null){if($clientId===''||$clientSecret===''||$refreshToken==='')throw new InvalidArgumentException('Gmail OAuth credentials are incomplete.');$this->transport=$transport??static function(string $method,string $url,array $headers,?string $body):array{$ch=curl_init($url);if($ch===false)throw new RuntimeException('Failed to initialize Gmail HTTP client.');$lines=[];foreach($headers as $k=>$v)$lines[]=$k.': '.$v;$opts=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_TIMEOUT=>30,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_HTTPHEADER=>$lines];if($body!==null)$opts[CURLOPT_POSTFIELDS]=$body;curl_setopt_array($ch,$opts);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$err=curl_error($ch);curl_close($ch);if(!is_string($raw))throw new RuntimeException('Gmail transport failure: '.$err);$json=json_decode($raw,true);return ['status'=>$status,'json'=>is_array($json)?$json:[]];};}
public function listMessages(string $query,?string $pageToken=null,int $maxResults=100): array{$params=['q'=>$query,'maxResults'=>max(1,min(500,$maxResults))];if($pageToken!==null&&$pageToken!=='')$params['pageToken']=$pageToken;$j=$this->authorizedJson('GET','https://gmail.googleapis.com/gmail/v1/users/'.rawurlencode($this->user).'/messages?'.http_build_query($params,'','&',PHP_QUERY_RFC3986));return ['messages'=>is_array($j['messages']??null)?$j['messages']:[],'nextPageToken'=>isset($j['nextPageToken'])?(string)$j['nextPageToken']:null,'resultSizeEstimate'=>(int)($j['resultSizeEstimate']??0)];}
public function getMessage(string $messageId): array{return $this->authorizedJson('GET','https://gmail.googleapis.com/gmail/v1/users/'.rawurlencode($this->user).'/messages/'.rawurlencode($messageId).'?format=full');}
private function authorizedJson(string $method,string $url): array{$r=($this->transport)($method,$url,['Authorization'=>'Bearer '.$this->token(),'Accept'=>'application/json'],null);if($r['status']<200||$r['status']>=300)throw new RuntimeException('Gmail API HTTP '.$r['status']);return $r['json'];}
private function token(): string{if($this->accessToken!==null)return $this->accessToken;$body=http_build_query(['grant_type'=>'refresh_token','refresh_token'=>$this->refreshToken,'client_id'=>$this->clientId,'client_secret'=>$this->clientSecret],'','&',PHP_QUERY_RFC3986);$r=($this->transport)('POST','https://oauth2.googleapis.com/token',['Content-Type'=>'application/x-www-form-urlencoded','Accept'=>'application/json'],$body);$token=trim((string)($r['json']['access_token']??''));if($r['status']!==200||$token==='')throw new RuntimeException('Failed to refresh Gmail OAuth token.');return $this->accessToken=$token;}}
