<?php
declare(strict_types=1);
function sv_ar_job_backoff_seconds(int $attempt): int { if($attempt<=0)return 30;return min(3600,60*(2**($attempt-1))); }
function sv_ar_job_priority(array $job): int { $action=strtoupper(trim((string)($job['action_type']??$job['job_type']??'RECONCILE')));$hours=max(0,(int)($job['hours_to_deadline']??9999));$risk=max(0.0,(float)($job['risk_amount']??0));if(in_array($action,['RESPOND_INFO_REQUEST','APPEAL_SAFE_T'],true)&&$hours<=24)return 0;$base=match($action){'RESPOND_INFO_REQUEST'=>10,'APPEAL_SAFE_T'=>15,'OPEN_SAFE_T'=>30,'RECONCILE'=>80,default=>60};$deadlineBonus=min(30,intdiv(max(0,168-min($hours,168)),6));$riskBonus=min(25,(int)floor($risk/100.0));return max(1,$base-$deadlineBonus-$riskBonus); }
function sv_ar_enqueue_job_db(PDO $db,string $jobType,?int $caseId,array $payload,string $idempotencyKey,int $priority=100,?DateTimeImmutable $availableAt=null): int { $json=json_encode($payload,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$when=($availableAt??new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('Y-m-d H:i:s');$s=$db->prepare("INSERT INTO amazon_recovery_jobs (job_type,case_id,idempotency_key,payload_json,priority,status,available_at) VALUES (?,?,?,?,?,'queued',?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id), priority=LEAST(priority,VALUES(priority)), available_at=LEAST(available_at,VALUES(available_at))");$s->execute([strtoupper($jobType),$caseId,$idempotencyKey,$json,$priority,$when]);return (int)$db->lastInsertId(); }
function sv_ar_claim_jobs_db(PDO $db,string $worker,int $limit=5,int $leaseSeconds=300): array { $limit=max(1,min(100,$limit));$leaseSeconds=max(30,min(3600,$leaseSeconds));$db->beginTransaction();try{$s=$db->prepare("SELECT * FROM amazon_recovery_jobs WHERE status='queued' AND available_at<=NOW() AND (lease_until IS NULL OR lease_until<NOW()) ORDER BY priority,available_at,id LIMIT {$limit} FOR UPDATE SKIP LOCKED");$s->execute();$rows=$s->fetchAll(PDO::FETCH_ASSOC);if($rows===[]){$db->commit();return [];} $ids=array_map(static fn(array $r):int=>(int)$r['id'],$rows);$ph=implode(',',array_fill(0,count($ids),'?'));$until=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->modify("+{$leaseSeconds} seconds")->format('Y-m-d H:i:s');$u=$db->prepare("UPDATE amazon_recovery_jobs SET status='running',lease_owner=?,lease_until=?,attempts=attempts+1,updated_at=NOW() WHERE id IN ({$ph})");$u->execute(array_merge([$worker,$until],$ids));foreach($rows as &$r){$r['status']='running';$r['lease_owner']=$worker;$r['lease_until']=$until;$r['attempts']=(int)$r['attempts']+1;}unset($r);$db->commit();return $rows;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;} }
function sv_ar_complete_job_db(PDO $db,int $jobId): bool { $s=$db->prepare("UPDATE amazon_recovery_jobs SET status='done',lease_owner=NULL,lease_until=NULL,last_error=NULL,updated_at=NOW() WHERE id=?");return $s->execute([$jobId]); }
function sv_ar_retry_job_db(PDO $db,int $jobId,string $error): string { $db->beginTransaction();try{$s=$db->prepare('SELECT id,attempts,max_attempts,job_type,case_id,idempotency_key,payload_json FROM amazon_recovery_jobs WHERE id=? FOR UPDATE');$s->execute([$jobId]);$r=$s->fetch(PDO::FETCH_ASSOC);if(!is_array($r)){$db->rollBack();return 'missing';}$attempts=(int)$r['attempts'];$max=(int)$r['max_attempts'];if($attempts>=$max){$d=$db->prepare('INSERT INTO amazon_recovery_dlq (original_job_id,case_id,job_type,idempotency_key,payload_json,attempts,last_error) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE last_error=VALUES(last_error),attempts=GREATEST(attempts,VALUES(attempts)),failed_at=NOW()');$d->execute([(int)$r['id'],$r['case_id']!==null?(int)$r['case_id']:null,(string)$r['job_type'],(string)$r['idempotency_key'],(string)$r['payload_json'],$attempts,$error]);$f=$db->prepare("UPDATE amazon_recovery_jobs SET status='failed',lease_owner=NULL,lease_until=NULL,last_error=?,updated_at=NOW() WHERE id=?");$f->execute([$error,$jobId]);$db->commit();return 'dlq';}$available=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->modify('+'.sv_ar_job_backoff_seconds(max(1,$attempts)).' seconds')->format('Y-m-d H:i:s');$q=$db->prepare("UPDATE amazon_recovery_jobs SET status='queued',available_at=?,lease_owner=NULL,lease_until=NULL,last_error=?,updated_at=NOW() WHERE id=?");$q->execute([$available,$error,$jobId]);$db->commit();return 'queued';}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;} }
function sv_ar_reap_stale_jobs_db(PDO $db): int { $s=$db->prepare("UPDATE amazon_recovery_jobs SET status='queued',lease_owner=NULL,lease_until=NULL,last_error='stale_lease_reaped',updated_at=NOW() WHERE status='running' AND lease_until IS NOT NULL AND lease_until<NOW()");$s->execute();return $s->rowCount(); }
