<?php
declare(strict_types=1);

/** @return list<string> */
function sv_ar_schema_statements(string $driver='mysql'): array
{
    $driver=strtolower($driver);
    if ($driver!=='mysql') throw new InvalidArgumentException('Amazon recovery production schema currently supports MySQL only.');
    return [
        "CREATE TABLE IF NOT EXISTS amazon_recovery_cases (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_key CHAR(64) NOT NULL,amazon_order_id VARCHAR(32) NOT NULL,amazon_order_item_id VARCHAR(128) NOT NULL DEFAULT '',refund_event_id VARCHAR(160) NOT NULL DEFAULT '',seller_sku VARCHAR(128) NULL,asin VARCHAR(32) NULL,quantity_ordered INT NOT NULL DEFAULT 0,quantity_refunded INT NOT NULL DEFAULT 0,quantity_received INT NOT NULL DEFAULT 0,marketplace_id VARCHAR(32) NOT NULL,fulfillment_channel VARCHAR(32) NULL,amazon_program VARCHAR(64) NULL,claim_reason VARCHAR(64) NOT NULL,refund_at DATETIME NULL,refund_initiator VARCHAR(64) NOT NULL DEFAULT 'UNKNOWN',eligibility_at DATETIME NULL,policy_version_id BIGINT UNSIGNED NULL,safe_t_id VARCHAR(64) NULL,case_state VARCHAR(64) NOT NULL DEFAULT 'OBSERVING',risk_amount DECIMAL(14,2) NOT NULL DEFAULT 0,expected_recovery DECIMAL(14,2) NOT NULL DEFAULT 0,approved_recovery DECIMAL(14,2) NOT NULL DEFAULT 0,received_recovery DECIMAL(14,2) NOT NULL DEFAULT 0,confidence VARCHAR(16) NOT NULL DEFAULT 'LOW',requires_human_review TINYINT(1) NOT NULL DEFAULT 0,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_case_key (case_key),KEY idx_amazon_recovery_case_order (amazon_order_id),KEY idx_amazon_recovery_case_state (case_state,eligibility_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_events (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(64) NOT NULL,source VARCHAR(32) NOT NULL,source_id VARCHAR(191) NOT NULL,observed_at DATETIME NOT NULL,effective_at DATETIME NOT NULL,payload_json JSON NULL,payload_hash CHAR(64) NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_source_event (source,source_id,event_type),KEY idx_amazon_recovery_events_case_time (case_id,effective_at,id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_ledger (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_id BIGINT UNSIGNED NOT NULL,transaction_id VARCHAR(191) NOT NULL,transaction_type VARCHAR(64) NOT NULL,amount DECIMAL(14,2) NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'BRL',posted_at DATETIME NULL,source_payload_json JSON NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_transaction (transaction_id,transaction_type),KEY idx_amazon_recovery_ledger_case (case_id,posted_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_policies (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,policy_key VARCHAR(128) NOT NULL,version INT NOT NULL,marketplace_id VARCHAR(32) NOT NULL,amazon_program VARCHAR(64) NULL,fulfillment_channel VARCHAR(32) NULL,claim_reason VARCHAR(64) NOT NULL,effective_from DATETIME NOT NULL,effective_to DATETIME NULL,basis_field VARCHAR(64) NOT NULL,wait_days INT NOT NULL,business_days TINYINT(1) NOT NULL DEFAULT 0,source_ref TEXT NOT NULL,source_hash CHAR(64) NULL,status VARCHAR(16) NOT NULL DEFAULT 'candidate',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_policy_version (policy_key,version),KEY idx_amazon_recovery_policy_lookup (marketplace_id,claim_reason,status,effective_from)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_jobs (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,job_type VARCHAR(64) NOT NULL,case_id BIGINT UNSIGNED NULL,idempotency_key CHAR(64) NOT NULL,payload_json JSON NOT NULL,priority INT NOT NULL DEFAULT 100,status VARCHAR(16) NOT NULL DEFAULT 'queued',available_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,lease_owner VARCHAR(128) NULL,lease_until DATETIME NULL,attempts INT NOT NULL DEFAULT 0,max_attempts INT NOT NULL DEFAULT 8,last_error TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_job_key (idempotency_key),KEY idx_amazon_recovery_job_claim (status,priority,available_at,lease_until)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_outbox (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_id BIGINT UNSIGNED NOT NULL,action_type VARCHAR(64) NOT NULL,idempotency_key CHAR(64) NOT NULL,payload_json JSON NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending',attempt_count INT NOT NULL DEFAULT 0,external_reference VARCHAR(191) NULL,last_error TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_outbox_key (idempotency_key),KEY idx_amazon_recovery_outbox_status (status,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_dlq (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,original_job_id BIGINT UNSIGNED NULL,case_id BIGINT UNSIGNED NULL,job_type VARCHAR(64) NOT NULL,idempotency_key CHAR(64) NOT NULL,payload_json JSON NOT NULL,attempts INT NOT NULL,last_error TEXT NOT NULL,failed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,resolved_at DATETIME NULL,resolution_note TEXT NULL,UNIQUE KEY uq_amazon_recovery_dlq_key (idempotency_key)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_evidence (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,case_id BIGINT UNSIGNED NOT NULL,evidence_type VARCHAR(64) NOT NULL,source VARCHAR(32) NOT NULL,source_id VARCHAR(191) NOT NULL,storage_ref TEXT NULL,metadata_json JSON NULL,payload_hash CHAR(64) NOT NULL,captured_at DATETIME NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_evidence_source (source,source_id,payload_hash),KEY idx_amazon_recovery_evidence_case (case_id,captured_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_inbox (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,source VARCHAR(32) NOT NULL,source_id VARCHAR(191) NOT NULL,event_type VARCHAR(64) NOT NULL,amazon_order_id VARCHAR(32) NULL,safe_t_id VARCHAR(64) NULL,effective_at DATETIME NULL,payload_json JSON NOT NULL,payload_hash CHAR(64) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'pending',last_error TEXT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_amazon_recovery_inbox_source (source,source_id,event_type),KEY idx_amazon_recovery_inbox_status (status,created_at),KEY idx_amazon_recovery_inbox_order (amazon_order_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_inbox_links (inbox_id BIGINT UNSIGNED NOT NULL,case_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (inbox_id,case_id),KEY idx_amazon_recovery_inbox_links_case (case_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
        "CREATE TABLE IF NOT EXISTS amazon_recovery_source_cursors (source_name VARCHAR(64) NOT NULL PRIMARY KEY,cursor_value TEXT NULL,checkpoint_at DATETIME NULL,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4",
    ];
}
function sv_ar_ensure_schema(PDO $db): void { $driver=(string)$db->getAttribute(PDO::ATTR_DRIVER_NAME);foreach(sv_ar_schema_statements($driver) as $sql)$db->exec($sql); }
