<?php
declare(strict_types=1);
require_once __DIR__.'/events.php';
function sv_ar_json(mixed $value): string { return json_encode($value,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_PRESERVE_ZERO_FRACTION|JSON_THROW_ON_ERROR); }
function sv_ar_mysql_datetime(mixed $value): ?string { if($value===null||trim((string)$value)==='')return null;return (new DateTimeImmutable((string)$value))->format('Y-m-d H:i:s'); }
function sv_ar_find_or_create_case(PDO $db,array $case): int {
    $key=sv_ar_case_key($case);$stmt=$db->prepare('INSERT INTO amazon_recovery_cases (case_key,amazon_order_id,amazon_order_item_id,refund_event_id,seller_sku,asin,quantity_ordered,quantity_refunded,quantity_received,marketplace_id,fulfillment_channel,amazon_program,claim_reason,refund_at,refund_initiator,risk_amount,expected_recovery,confidence,requires_human_review) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id), seller_sku=COALESCE(VALUES(seller_sku),seller_sku), asin=COALESCE(VALUES(asin),asin), quantity_ordered=GREATEST(quantity_ordered,VALUES(quantity_ordered)), quantity_refunded=GREATEST(quantity_refunded,VALUES(quantity_refunded)), risk_amount=GREATEST(risk_amount,VALUES(risk_amount)), expected_recovery=GREATEST(expected_recovery,VALUES(expected_recovery)), updated_at=NOW()');
    $stmt->execute([$key,(string)$case['amazon_order_id'],(string)($case['amazon_order_item_id']??''),(string)($case['refund_event_id']??''),($case['seller_sku']??null)?:null,($case['asin']??null)?:null,(int)($case['quantity_ordered']??0),(int)($case['quantity_refunded']??0),(int)($case['quantity_received']??0),(string)($case['marketplace_id']??''),($case['fulfillment_channel']??null)?:null,($case['amazon_program']??null)?:null,strtoupper((string)$case['claim_reason']),sv_ar_mysql_datetime($case['refund_at']??null),(string)($case['refund_initiator']??'UNKNOWN'),round((float)($case['risk_amount']??0),2),round((float)($case['expected_recovery']??$case['risk_amount']??0),2),(string)($case['confidence']??'LOW'),!empty($case['requires_human_review'])?1:0]);return (int)$db->lastInsertId(); }
function sv_ar_append_event_db(PDO $db,int $caseId,array $event): int { $payload=is_array($event['payload']??null)?$event['payload']:[];$hash=hash('sha256',sv_ar_json($payload));$stmt=$db->prepare('INSERT INTO amazon_recovery_events (case_id,event_type,source,source_id,observed_at,effective_at,payload_hash,payload_json) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$stmt->execute([$caseId,strtoupper((string)$event['event_type']),strtolower((string)$event['source']),(string)$event['source_id'],sv_ar_mysql_datetime($event['observed_at']??'now'),sv_ar_mysql_datetime($event['effective_at']??$event['observed_at']??'now'),$hash,sv_ar_json($payload)]);return (int)$db->lastInsertId(); }
function sv_ar_record_ledger_db(PDO $db,int $caseId,array $entry): int { $stmt=$db->prepare('INSERT INTO amazon_recovery_ledger (case_id,transaction_id,transaction_type,amount,currency,posted_at,source_payload_json) VALUES (?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$stmt->execute([$caseId,(string)$entry['transaction_id'],strtoupper((string)($entry['type']??$entry['transaction_type']??'UNKNOWN')),round(abs((float)($entry['amount']??0)),2),strtoupper((string)($entry['currency']??'BRL')),sv_ar_mysql_datetime($entry['posted_at']??null),sv_ar_json($entry['raw']??$entry)]);return (int)$db->lastInsertId(); }
function sv_ar_store_evidence(PDO $db,int $caseId,array $evidence): int { $content=(string)($evidence['content']??sv_ar_json($evidence['metadata']??[]));$hash=hash('sha256',$content);$stmt=$db->prepare('INSERT INTO amazon_recovery_evidence (case_id,evidence_type,source,source_id,storage_ref,metadata_json,payload_hash,captured_at) VALUES (?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)');$stmt->execute([$caseId,strtoupper((string)$evidence['evidence_type']),strtolower((string)$evidence['source']),(string)$evidence['source_id'],$evidence['storage_ref']??null,sv_ar_json($evidence['metadata']??[]),$hash,sv_ar_mysql_datetime($evidence['captured_at']??'now')]);return (int)$db->lastInsertId(); }
function sv_ar_apply_snapshot(PDO $db,int $caseId,array $snapshot): bool { $stmt=$db->prepare('UPDATE amazon_recovery_cases SET case_state=?,eligibility_at=?,safe_t_id=?,expected_recovery=?,approved_recovery=?,received_recovery=?,confidence=?,requires_human_review=?,updated_at=NOW() WHERE id=?');return $stmt->execute([(string)($snapshot['case_state']??'OBSERVING'),sv_ar_mysql_datetime($snapshot['eligibility_at']??null),($snapshot['safe_t_id']??null)?:null,round((float)($snapshot['expected_recovery']??$snapshot['financial']['expected_recovery']??0),2),round((float)($snapshot['approved_recovery']??$snapshot['financial']['approved_recovery']??0),2),round((float)($snapshot['received_recovery']??$snapshot['financial']['received_recovery']??0),2),(string)($snapshot['confidence']??'LOW'),!empty($snapshot['requires_human_review'])?1:0,$caseId]); }
function sv_ar_fetch_case(PDO $db,int $caseId): ?array { $s=$db->prepare('SELECT * FROM amazon_recovery_cases WHERE id=? LIMIT 1');$s->execute([$caseId]);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:null; }
function sv_ar_fetch_events(PDO $db,int $caseId): array { $s=$db->prepare('SELECT event_type,source,source_id,observed_at,effective_at,payload_json FROM amazon_recovery_events WHERE case_id=? ORDER BY effective_at,id');$s->execute([$caseId]);$out=[];foreach($s->fetchAll(PDO::FETCH_ASSOC) as $r){$r['payload']=json_decode((string)($r['payload_json']??'{}'),true)?:[];unset($r['payload_json']);$out[]=$r;}return $out; }
function sv_ar_fetch_ledger(PDO $db,int $caseId): array { $s=$db->prepare('SELECT transaction_id,transaction_type AS type,amount,currency,posted_at,source_payload_json FROM amazon_recovery_ledger WHERE case_id=? ORDER BY posted_at,id');$s->execute([$caseId]);return $s->fetchAll(PDO::FETCH_ASSOC); }
function sv_ar_fetch_evidence(PDO $db,int $caseId): array { $s=$db->prepare('SELECT id,evidence_type AS type,source,source_id,storage_ref,metadata_json,payload_hash,captured_at FROM amazon_recovery_evidence WHERE case_id=? ORDER BY captured_at,id');$s->execute([$caseId]);return $s->fetchAll(PDO::FETCH_ASSOC); }
