<?php
declare(strict_types=1);
require __DIR__.'/amazon-recovery-testlib.php';
require __DIR__.'/../includes/amazon-recovery/storage.php';
final class ArStorageStmt extends PDOStatement { public array $params=[];public array $rows=[];protected function __construct(){}public static function make(array $rows=[]):self{$s=new self();$s->rows=$rows;return $s;}public function execute(?array $params=null):bool{$this->params=$params??[];return true;}public function fetch(int $mode=PDO::FETCH_DEFAULT,int $cursorOrientation=PDO::FETCH_ORI_NEXT,int $cursorOffset=0):mixed{return $this->rows[0]??false;}public function fetchAll(int $mode=PDO::FETCH_DEFAULT,mixed ...$args):array{return $this->rows;} }
final class ArStoragePdo extends PDO { public array $prepared=[];public array $queueRows=[];public int $nextId=100;public function __construct(){}public function prepare(string $query,array $options=[]):PDOStatement|false{$s=ArStorageStmt::make(array_shift($this->queueRows)??[]);$this->prepared[]=['sql'=>$query,'stmt'=>$s];return $s;}public function lastInsertId(?string $name=null):string|false{return (string)$this->nextId++;} }
$db=new ArStoragePdo();$caseId=sv_ar_find_or_create_case($db,['amazon_order_id'=>'702-1111111-2222222','amazon_order_item_id'=>'oi1','refund_event_id'=>'rf1','marketplace_id'=>'A2Q3Y263D00KWC','claim_reason'=>'RETURN_NOT_RECEIVED','risk_amount'=>128.25]);ar_t_eq(100,$caseId,'case id');ar_t_assert(str_contains($db->prepared[0]['sql'],'ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)'),'case idempotent');
$eventId=sv_ar_append_event_db($db,$caseId,['event_type'=>'REFUND_DETECTED','source'=>'gmail','source_id'=>'m1','observed_at'=>'2026-09-01 10:00:00','effective_at'=>'2026-08-01 10:00:00','payload'=>['amount'=>128.25]]);ar_t_eq(101,$eventId,'event id');ar_t_eq(64,strlen((string)$db->prepared[1]['stmt']->params[6]),'event hash');
$ledgerId=sv_ar_record_ledger_db($db,$caseId,['transaction_id'=>'tx1','type'=>'AMAZON_PROACTIVE_REIMBURSEMENT','amount'=>128.25,'currency'=>'BRL','posted_at'=>'2026-09-01 12:00:00','raw'=>['x'=>1]]);ar_t_eq(102,$ledgerId,'ledger id');
$evId=sv_ar_store_evidence($db,$caseId,['evidence_type'=>'EMAIL','source'=>'gmail','source_id'=>'m1','metadata'=>['subject'=>'x'],'captured_at'=>'2026-09-01 12:00:00','content'=>'evidence']);ar_t_eq(103,$evId,'evidence id');ar_t_eq(64,strlen((string)$db->prepared[3]['stmt']->params[6]),'evidence hash');
ar_t_eq(true,sv_ar_apply_snapshot($db,$caseId,['case_state'=>'WAITING_ELIGIBILITY','eligibility_at'=>'2026-09-15T12:00:00-03:00','expected_recovery'=>128.25,'confidence'=>'HIGH']),'snapshot update');ar_t_ok('PDO storage contracts');
