<?php
declare(strict_types=1);
require __DIR__.'/amazon-recovery-testlib.php';
require __DIR__.'/../includes/amazon-recovery/jobs.php';require __DIR__.'/../includes/amazon-recovery/outbox.php';
final class ArDurableStmt extends PDOStatement { public array $params=[];public array $rows=[];protected function __construct(){}public static function make(array $rows=[]):self{$s=new self();$s->rows=$rows;return $s;}public function execute(?array $params=null):bool{$this->params=$params??[];return true;}public function fetch(int $mode=PDO::FETCH_DEFAULT,int $cursorOrientation=PDO::FETCH_ORI_NEXT,int $cursorOffset=0):mixed{return array_shift($this->rows)?:false;}public function fetchAll(int $mode=PDO::FETCH_DEFAULT,mixed ...$args):array{return $this->rows;} }
final class ArDurablePdo extends PDO { public array $prepared=[];public array $rowQueue=[];public int $nextId=200;public bool $tx=false;public function __construct(){}public function prepare(string $query,array $options=[]):PDOStatement|false{$s=ArDurableStmt::make(array_shift($this->rowQueue)??[]);$this->prepared[]=['sql'=>$query,'stmt'=>$s];return $s;}public function lastInsertId(?string $name=null):string|false{return (string)$this->nextId++;}public function beginTransaction():bool{$this->tx=true;return true;}public function commit():bool{$this->tx=false;return true;}public function rollBack():bool{$this->tx=false;return true;}public function inTransaction():bool{return $this->tx;} }
$db=new ArDurablePdo();ar_t_eq(200,sv_ar_enqueue_job_db($db,'RECONCILE',10,['x'=>1],'job-key',50,new DateTimeImmutable('2026-09-01T12:00:00Z')),'job id');ar_t_assert(str_contains($db->prepared[0]['sql'],'ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id)'),'job idempotent');
$case=['amazon_order_id'=>'701-1111111-2222222','amazon_order_item_id'=>'i1','refund_event_id'=>'r1','claim_reason'=>'RETURN_NOT_RECEIVED'];ar_t_eq(201,sv_ar_schedule_action_db($db,10,$case,'OPEN_SAFE_T',['claim'=>'x']),'outbox id');sv_ar_mark_action_uncertain($db,201,'timeout after submit');ar_t_assert(str_contains($db->prepared[2]['sql'],"status='uncertain'"),'uncertain explicit');sv_ar_confirm_action($db,201,'safe-t-1');ar_t_assert(str_contains($db->prepared[3]['sql'],"status='confirmed'"),'confirm explicit');
$db2=new ArDurablePdo();$db2->rowQueue[]=[['id'=>5,'attempts'=>2,'max_attempts'=>5,'job_type'=>'RECONCILE','case_id'=>10,'idempotency_key'=>'k','payload_json'=>'{}']];ar_t_eq('queued',sv_ar_retry_job_db($db2,5,'network'),'retryable requeued');
$db3=new ArDurablePdo();$db3->rowQueue[]=[['id'=>6,'attempts'=>5,'max_attempts'=>5,'job_type'=>'OPEN_SAFE_T','case_id'=>10,'idempotency_key'=>'k2','payload_json'=>'{}']];ar_t_eq('dlq',sv_ar_retry_job_db($db3,6,'permanent'),'exhausted to DLQ');ar_t_assert(str_contains($db3->prepared[1]['sql'],'amazon_recovery_dlq'),'DLQ insert');ar_t_ok('durable jobs and outbox');
