<?php
declare(strict_types=1);
require __DIR__.'/amazon-recovery-testlib.php';
require __DIR__.'/../includes/marketplace/AmazonClient.php';
require __DIR__.'/../includes/amazon-recovery/amazon-orders.php';
require __DIR__.'/../includes/amazon-recovery/amazon-finances.php';
require __DIR__.'/../includes/amazon-recovery/amazon-reports.php';
require __DIR__.'/../includes/amazon-recovery/amazon-notifications.php';
ar_t_assert(interface_exists('SvAmazonApi'),'shared Amazon API interface exists');ar_t_assert(class_exists('SvAmazonClient'),'shared client exists');ar_t_assert(is_subclass_of('SvAmazonClient','SvAmazonApi'),'client implements transport');
$publisher=(string)file_get_contents(__DIR__.'/../includes/marketplace/AmazonPublisher.php');ar_t_eq(0,substr_count($publisher,'class SvAmazonClient'),'publisher must not redefine shared client');ar_t_assert(str_contains($publisher,"require_once __DIR__ . '/AmazonClient.php';"),'publisher imports shared client');
final class ArFakeAmazonApi implements SvAmazonApi { public array $calls=[]; public function request(string $method,string $path,array $query=[],?array $body=null):array{$this->calls[]=compact('method','path','query','body');if(str_contains($path,'/finances/'))return ['status'=>200,'request_id'=>'fin-1','data'=>['transactions'=>[['transactionId'=>'tx1','transactionType'=>'Refund','transactionStatus'=>'RELEASED','totalAmount'=>['currencyAmount'=>128.25,'currencyCode'=>'BRL'],'relatedIdentifiers'=>[['relatedIdentifierName'=>'ORDER_ID','relatedIdentifierValue'=>'701-1433354-4637803']]]]]];if($method==='POST'&&$path==='/reports/2021-06-30/reports')return ['status'=>202,'request_id'=>'rep-1','data'=>['reportId'=>'rpt1']];return ['status'=>200,'request_id'=>'ord-1','data'=>['order'=>['orderId'=>'701-1433354-4637803','createdTime'=>'2026-08-20T00:00:00Z','salesChannel'=>['marketplaceId'=>'A2Q3Y263D00KWC'],'programs'=>['DELIVERY_BY_AMAZON'],'orderItems'=>[['orderItemId'=>'oi1','quantityOrdered'=>1,'product'=>['asin'=>'B0ABCDEF12','sellerSku'=>'SKU1']]]]]];} public function sellerId():string{return 'SELLER';} public function marketplaceId():string{return 'A2Q3Y263D00KWC';}}
$fake=new ArFakeAmazonApi();$orders=new SvAmazonRecoveryOrders($fake);$order=$orders->getOrder('701-1433354-4637803');ar_t_eq('DELIVERY_BY_AMAZON',$order['amazon_program'],'program normalized');ar_t_eq('SKU1',$order['items'][0]['seller_sku'],'sku normalized');ar_t_eq('/orders/2026-01-01/orders/701-1433354-4637803',$fake->calls[0]['path'],'current Orders API path');ar_t_assert(str_contains($fake->calls[0]['query']['includedData'],'PACKAGES'),'tracking/package data requested');
$fin=new SvAmazonRecoveryFinances($fake);$tx=$fin->listByOrder('701-1433354-4637803');ar_t_eq('tx1',$tx[0]['transaction_id'],'finance normalized');ar_t_eq('ORDER_ID',$fake->calls[1]['query']['relatedIdentifierName'],'finance filters ORDER_ID');
$reports=new SvAmazonRecoveryReports($fake);ar_t_eq('rpt1',$reports->requestReturnReport('GET_FLAT_FILE_RETURNS_DATA_BY_RETURN_DATE',new DateTimeImmutable('2026-08-01T00:00:00Z'),new DateTimeImmutable('2026-09-01T00:00:00Z')),'report id returned');ar_t_eq('/reports/2021-06-30/reports',$fake->calls[2]['path'],'current reports path');
$n=sv_ar_normalize_amazon_notification(['notificationType'=>'TRANSACTION_UPDATE','payload'=>['transactionId'=>'tx9']]);ar_t_eq('TRANSACTION_UPDATE',$n['event_type'],'transaction update normalized');ar_t_ok('Amazon SP-API adapters contract');
