import http from 'node:http';
import { spawn } from 'node:child_process';
import { timingSafeEqual } from 'node:crypto';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
const ROOT=dirname(fileURLToPath(import.meta.url));
const TOKEN=process.env.SHOPVIVALIZ_REMOTE_MCP_TOKEN||'';
if(!TOKEN) throw new Error('mcp_token_unavailable');
const tools=[
  {name:'browser_universal_tabs_list',description:'List saved logical tabs; pages reload when switched',inputSchema:{type:'object',properties:{},additionalProperties:false}},
  {name:'browser_universal_tabs_open',description:'Add a logical tab and visit a public URL',inputSchema:{type:'object',properties:{url:{type:'string'}},required:['url'],additionalProperties:false}},
  {name:'browser_universal_tabs_switch',description:'Restore a logical tab by navigating to its saved URL',inputSchema:{type:'object',properties:{tab_id:{type:'string'}},required:['tab_id'],additionalProperties:false}},
  {name:'browser_universal_tabs_close',description:'Close a saved logical tab',inputSchema:{type:'object',properties:{tab_id:{type:'string'}},required:['tab_id'],additionalProperties:false}},
  {name:'browser_universal_probe',description:'Run isolated browser smoke test',inputSchema:{type:'object',properties:{},additionalProperties:false}},
  {name:'browser_universal_open',description:'Open a URL in isolated Chrome and return title',inputSchema:{type:'object',properties:{url:{type:'string'}},required:['url'],additionalProperties:false}},
  {name:'browser_universal_inspect',description:'Inspect sanitized page interactive controls',inputSchema:{type:'object',properties:{url:{type:'string'}},required:['url'],additionalProperties:false}},
  {name:'browser_universal_click',description:'Click CSS selector on an authorized URL',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'}},required:['url','selector'],additionalProperties:false}},
  {name:'browser_universal_fill',description:'Fill a non-sensitive field on an authorized URL',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'},text:{type:'string'}},required:['url','selector','text'],additionalProperties:false}},
  {name:'browser_universal_select',description:'Select one option on an authorized URL',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'},value:{type:'string'}},required:['url','selector','value'],additionalProperties:false}},
  {name:'browser_universal_check',description:'Check one checkbox on an authorized URL',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'}},required:['url','selector'],additionalProperties:false}},
  {name:'browser_universal_press',description:'Press a restricted navigation key on an authorized URL',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'},key:{type:'string',enum:['Enter','Tab','Escape','ArrowUp','ArrowDown','Space']}},required:['url','selector','key'],additionalProperties:false}},
  {name:'browser_universal_upload',description:'Attach a staged file under the isolated upload-staging directory',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'},filename:{type:'string'}},required:['url','selector','filename'],additionalProperties:false}},
  {name:'browser_universal_download',description:'Download by clicking a specified element and save under the isolated downloads directory',inputSchema:{type:'object',properties:{url:{type:'string'},selector:{type:'string'}},required:['url','selector'],additionalProperties:false}}
];
function authorized(raw){const supplied=(raw||'').replace(/^Bearer /i,'');const a=Buffer.from(supplied);const b=Buffer.from(TOKEN);return a.length===b.length && timingSafeEqual(a,b)}
let browserBusy=false;
async function runTool(name,args){if(browserBusy) throw Error('browser_busy');browserBusy=true;try{return await spawnBrowser(name,args)}finally{browserBusy=false}}
function spawnBrowser(name,args){return new Promise((resolve,reject)=>{const action=name.replace('browser_universal_','');if(!tools.some(t=>t.name===name))return reject(Error('unknown_tool'));const proc=spawn(process.execPath,[ROOT+'/universal-browser.mjs',action],{cwd:ROOT,stdio:['pipe','pipe','pipe'],env:{PATH:process.env.PATH||'/usr/local/bin:/usr/bin:/bin',HOME:'/home/ubuntu',LANG:'C.UTF-8'}});let out='',err='';const timeout=setTimeout(()=>proc.kill('SIGKILL'),45000);proc.stdout.on('data',x=>{out+=x.toString().slice(0,80000)});proc.stderr.on('data',x=>{err+=x.toString().slice(0,2000)});proc.on('error',reject);proc.on('close',code=>{clearTimeout(timeout);if(code!==0)return reject(Error('browser_failed:'+err.slice(0,250)));try{resolve(JSON.parse(out))}catch(e){reject(Error('invalid_browser_result'))}});proc.stdin.end(JSON.stringify(args||{}))})}
const server=http.createServer(async(req,res)=>{const send=(status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(obj))};if(req.socket.remoteAddress!=='127.0.0.1'&&req.socket.remoteAddress!=='::1')return send(403,{error:'loopback_only'});if(req.url==='/health'&&req.method==='GET')return send(200,{ok:true,endpoint:'browser-universal-mcp',tools:tools.length});if(req.url!=='/mcp'||req.method!=='POST')return send(404,{error:'not_found'});if(!authorized(req.headers.authorization))return send(401,{error:'unauthorized'});let data='';for await(const chunk of req){data+=chunk;if(data.length>30000)return send(413,{error:'too_large'})}try{const x=JSON.parse(data);let result;if(x.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'shopvivaliz-browser-universal',version:'0.1.0'}};else if(x.method==='tools/list')result={tools};else if(x.method==='tools/call'){const value=await runTool(x.params?.name,x.params?.arguments||{});result={content:[{type:'text',text:JSON.stringify(value)}],isError:false}}else if(x.method==='notifications/initialized'){res.writeHead(202);res.end();return}else return send(400,{jsonrpc:'2.0',id:x.id??null,error:{code:-32601,message:'unsupported_method'}});return send(200,{jsonrpc:'2.0',id:x.id??null,result})}catch(e){return send(200,{jsonrpc:'2.0',id:null,error:{code:-32000,message:String(e.message).slice(0,280)}})}});
server.listen(Number(process.env.SHOPVIVALIZ_BROWSER_UNIVERSAL_PORT||5595),'127.0.0.1');
