CREATE TABLE IF NOT EXISTS blog_articles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    slug VARCHAR(191) NOT NULL,
    title VARCHAR(255) NOT NULL,
    excerpt TEXT NOT NULL,
    category VARCHAR(120) NOT NULL,
    image_url VARCHAR(1000) NULL,
    image_alt VARCHAR(255) NULL,
    content_json LONGTEXT NOT NULL,
    faq_json LONGTEXT NULL,
    keywords_json TEXT NULL,
    meta_title VARCHAR(255) NULL,
    meta_description VARCHAR(320) NULL,
    related_products_url VARCHAR(1000) NULL,
    author VARCHAR(191) NOT NULL DEFAULT 'Equipe ShopVivaliz',
    status ENUM('draft','review','scheduled','published','archived') NOT NULL DEFAULT 'draft',
    featured TINYINT(1) NOT NULL DEFAULT 0,
    reading_time SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    published_at DATETIME NULL,
    scheduled_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_blog_articles_slug (slug),
    KEY idx_blog_articles_status_publish (status, published_at),
    KEY idx_blog_articles_status_schedule (status, scheduled_at),
    KEY idx_blog_articles_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
