<?php
declare(strict_types=1);
require_once __DIR__ . '/../../includes/admin-guard.php';
require_once __DIR__ . '/../../includes/csrf.php';
$csrf=sv_csrf_token('amazon_returns_intake');
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Registrar devolução Amazon</title>
<style>:root{font-family:Inter,system-ui,sans-serif;color:#17202a;background:#f4f6f8}*{box-sizing:border-box}body{margin:0}.wrap{max-width:720px;margin:auto;padding:18px}.panel{background:#fff;border:1px solid #e4e7ea;border-radius:14px;padding:18px;margin-bottom:14px}label{font-weight:700;display:block;margin:14px 0 6px}input,select,textarea,button{width:100%;font:inherit;padding:12px;border:1px solid #cfd4da;border-radius:10px}button{background:#17202a;color:#fff;font-weight:800;cursor:pointer}.row{display:grid;grid-template-columns:1fr auto;gap:8px}.row button{width:auto}.item{border:1px solid #e4e7ea;border-radius:10px;padding:12px;margin:8px 0;cursor:pointer}.item.active{border-color:#17202a;background:#f8fafc}.muted{color:#667085}.ok{color:#067647;font-weight:700}.err{color:#b42318;font-weight:700}.back{color:#17202a}@media(max-width:560px){.wrap{padding:10px}.panel{padding:14px}.row{grid-template-columns:1fr}.row button{width:100%}}</style></head><body><main class="wrap">
<p><a class="back" href="/admin/amazon-returns/">← Amazon Returns</a></p><h1>Registrar devolução recebida</h1>
<section class="panel"><label for="order">Pedido Amazon / RMA / código</label><div class="row"><input id="order" inputmode="numeric" placeholder="702-0000000-0000000" autocomplete="off"><button type="button" id="search">Localizar</button></div><div id="items"></div></section>
<form class="panel" id="form" enctype="multipart/form-data"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars($csrf,ENT_QUOTES,'UTF-8')?>"><input type="hidden" name="operation_id" id="operation"><input type="hidden" name="case_id" id="case_id">
<div id="selected" class="muted">Localize e selecione um item antes de registrar.</div>
<label for="quantity">Quantidade do item correto recebida</label><input id="quantity" name="quantity_correct" type="number" min="0" step="1" value="1" required><div class="muted">Produto diferente ou embalagem vazia: informe 0. Em devolução parcial, informe somente a quantidade correta que chegou.</div>
<label for="condition">Condição</label><select id="condition" name="condition" required><option value="OK">Íntegro</option><option value="DAMAGED">Danificado</option><option value="USED">Usado</option><option value="WRONG_ITEM">Produto diferente</option><option value="INCOMPLETE">Incompleto</option><option value="EMPTY_PACKAGE">Embalagem vazia</option></select>
<label for="note">Observação</label><textarea id="note" name="note" rows="4" maxlength="2000" placeholder="Descreva somente fatos observados na conferência."></textarea>
<label for="photos">Fotos da conferência</label><input id="photos" name="photos[]" type="file" accept="image/jpeg,image/png,image/webp" multiple><div class="muted">Obrigatórias quando houver qualquer divergência. Máximo de 6 fotos, 8 MB cada.</div>
<p id="message"></p><button type="submit">Confirmar recebimento físico</button></form></main>
<script>
const csrf=<?=json_encode($csrf,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT)?>;const operation=document.querySelector('#operation');const msg=document.querySelector('#message');const caseId=document.querySelector('#case_id');const selected=document.querySelector('#selected');const uuid=()=>crypto.randomUUID();operation.value=uuid();
function setMsg(t,ok=false){msg.textContent=t;msg.className=ok?'ok':'err'}
function choose(c,el){caseId.value=c.id;document.querySelectorAll('.item').forEach(x=>x.classList.remove('active'));el.classList.add('active');const pending=Math.max(0,Number(c.quantity_refunded)-Number(c.quantity_received));document.querySelector('#quantity').max=String(pending);document.querySelector('#quantity').value=String(Math.min(1,pending));selected.textContent=`${c.amazon_order_id} · ${c.sku||c.asin||c.amazon_order_item_id} · pendente: ${pending}`}
document.querySelector('#search').addEventListener('click',async()=>{msg.textContent='';const id=document.querySelector('#order').value.trim();if(!/^\d{3}-\d{7}-\d{7}$/.test(id)){setMsg('Informe um número de pedido Amazon válido.');return}const r=await fetch('/admin/amazon-returns/api/case.php?order_id='+encodeURIComponent(id),{cache:'no-store'});const j=await r.json();const box=document.querySelector('#items');box.replaceChildren();if(!r.ok||!j.success){setMsg(j.error||'Falha na consulta.');return}if(!(j.cases||[]).length){setMsg('Nenhum caso de devolução encontrado para este pedido.');return}for(const c of j.cases){const el=document.createElement('div');el.className='item';el.textContent=`${c.sku||c.asin||c.amazon_order_item_id} · ${c.state} · recebido ${c.quantity_received}/${c.quantity_refunded}`;el.addEventListener('click',()=>choose(c,el));box.append(el)}if(j.cases.length===1)box.firstElementChild.click()});
document.querySelector('#condition').addEventListener('change',e=>{const discrepancy=e.target.value!=='OK';document.querySelector('#photos').required=discrepancy;if(['WRONG_ITEM','EMPTY_PACKAGE'].includes(e.target.value))document.querySelector('#quantity').value='0'});
document.querySelector('#form').addEventListener('submit',async e=>{e.preventDefault();if(!caseId.value){setMsg('Selecione o item recebido.');return}const condition=document.querySelector('#condition').value;if(condition!=='OK'&&!document.querySelector('#photos').files.length){setMsg('Anexe ao menos uma foto da divergência.');return}const fd=new FormData(e.target);try{const r=await fetch('/admin/amazon-returns/api/intake.php',{method:'POST',body:fd,headers:{'X-CSRF-Token':csrf},credentials:'same-origin'});const j=await r.json();if(!r.ok||!j.success)throw new Error(j.error||'Falha ao registrar.');setMsg(j.duplicate?'Recebimento já havia sido registrado; nenhum evento foi duplicado.':'Recebimento físico registrado e caso recalculado.',true);operation.value=uuid();}catch(err){setMsg(err.message)}});
</script></body></html>
