<?php
declare(strict_types=1);

/**
 * Returns the GA4 client_id represented by the _ga cookie.
 *
 * Example cookie: GA1.1.123456789.1700000000
 * GA4 Measurement Protocol expects the client_id generated by the browser tag,
 * so we persist only the final "123456789.1700000000" portion in the order.
 */
function svorc_ga_client_id_from_cookie(): string {
    if (!hash_equals('accepted', (string)($_COOKIE['sv_privacy_consent'] ?? ''))) {
        return '';
    }

    $raw = trim((string)($_COOKIE['_ga'] ?? ''));
    if ($raw === '') {
        return '';
    }

    if (preg_match('/^GA\d+\.\d+\.(\d+\.\d+)$/', $raw, $match) === 1) {
        return (string)$match[1];
    }

    // Defensive support if an upstream layer already exposes only client_id.
    if (preg_match('/^\d+\.\d+$/', $raw) === 1) {
        return $raw;
    }

    return '';
}

/**
 * Returns the GA4 session cookie for the active web stream.
 *
 * Since February 2026 GA4 Measurement Protocol accepts the full session cookie
 * as session_id. Persisting it with the browser client_id lets the approved
 * server-side purchase join the same tagged session instead of becoming an
 * unattributed offline event. We only read it after explicit site consent.
 */
function svorc_ga_session_cookie(): string {
    if (!hash_equals('accepted', (string)($_COOKIE['sv_privacy_consent'] ?? ''))) {
        return '';
    }

    foreach ($_COOKIE as $name => $value) {
        if (!is_string($name) || !str_starts_with($name, '_ga_') || !is_scalar($value)) {
            continue;
        }

        $cookie = trim((string)$value);
        if ($cookie === '' || strlen($cookie) > 96) {
            continue;
        }

        // GA4 session cookies use GS* formats and can contain dots and "$".
        if (preg_match('/^GS\d+(?:\.\d+)?[A-Za-z0-9.$_-]*$/', $cookie) === 1) {
            return $cookie;
        }
    }

    return '';
}

/**
 * Keep the existing order field backwards compatible while carrying both
 * browser identifiers. The left side is always the canonical GA4 client_id;
 * the optional right side is the GA4 session cookie used by Measurement
 * Protocol. Existing orders containing only client_id remain valid.
 */
function svorc_pack_ga_identity(string $clientId, string $sessionCookie): string {
    if ($clientId === '') {
        return '';
    }

    $packed = $sessionCookie !== '' ? $clientId . '|' . $sessionCookie : $clientId;
    return strlen($packed) <= 128 ? $packed : $clientId;
}

/**
 * Recovers a Google Ads click id from the first-party conversion-linker cookie
 * when the browser payload did not carry one. This is only used after explicit
 * analytics/ad consent and never stores the whole cookie value.
 */
function svorc_gclid_from_cookie(): string {
    if (!hash_equals('accepted', (string)($_COOKIE['sv_privacy_consent'] ?? ''))) {
        return '';
    }

    $raw = trim((string)($_COOKIE['_gcl_aw'] ?? ''));
    if ($raw === '') {
        return '';
    }

    if (preg_match('/^GCL\.\d+\.(.+)$/', $raw, $match) !== 1) {
        return '';
    }

    $gclid = trim((string)$match[1]);
    if ($gclid === '' || strlen($gclid) > 255 || preg_match('/^[A-Za-z0-9._-]+$/', $gclid) !== 1) {
        return '';
    }

    return $gclid;
}

function svorc_set(array $body, array $resolvedItems): void {
    // The checkout historically sent a random first-party funnel id in this
    // field. For paid-media attribution, the approved purchase must use the
    // identifiers generated by the GA browser tag. Prefer the real _ga id and
    // its GA4 session cookie when consent exists; otherwise keep the original
    // fallback untouched.
    $gaClientId = svorc_ga_client_id_from_cookie();
    if ($gaClientId !== '') {
        $body['funnel_client_id'] = svorc_pack_ga_identity(
            $gaClientId,
            svorc_ga_session_cookie()
        );
    }

    if (trim((string)($body['gclid'] ?? '')) === '') {
        $cookieGclid = svorc_gclid_from_cookie();
        if ($cookieGclid !== '') {
            $body['gclid'] = $cookieGclid;
        }
    }

    $GLOBALS['shopvivaliz_order_body'] = $body;
    $GLOBALS['shopvivaliz_order_items'] = $resolvedItems;
}

function svorc_body(): array {
    $body = $GLOBALS['shopvivaliz_order_body'] ?? [];
    return is_array($body) ? $body : [];
}

function svorc_items(): array {
    $items = $GLOBALS['shopvivaliz_order_items'] ?? [];
    return is_array($items) ? $items : [];
}
