name: CI AUTONOMO CONTINUO

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

jobs:
  build:
    if: ${{ vars.ENABLE_GITHUB_HOSTED_RUNNERS == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Teste
        run: echo "CI OK"