name: Deploy Automático Inteligente - Shop Vivaliz

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Sincronizar com a HostGator
    runs-on: ubuntu-latest

    steps:
    - name: Baixar o código do repositório
      uses: actions/checkout@v4

    - name: Instalar LFTP no Servidor
      run: |
        sudo apt-get update
        sudo apt-get install lftp -y

    - name: Executar Sincronizacao Inteligente via LFTP
      env:
        USER: ${{ secrets.FTP_USERNAME }}
        PASS: ${{ secrets.FTP_PASSWORD }}
        HOST: ${{ secrets.FTP_SERVER }}
      run: |
        lftp -c "
        set ftp:ssl-allow no;
        open -u $USER,$PASS $HOST;
        mirror --reverse --delete --verbose ./ /public_html/;
        quit
        "
